# Generated by Django 5.1.2 on 2024-12-16 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_trade',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cant_trade_time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
