# Generated by Django 5.1.2 on 2024-12-25 04:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Tecnologico', 'Tecnologico'), ('Deportes', 'Deportes'), ('Juegos', 'Juegos'), ('Electrodomesticos', 'Electrodomesticos'), ('Automoviles', 'Automoviles'), ('Electrónica', 'Electrónica'), ('Muebles', 'Muebles'), ('Ropa y Accesorios', 'Ropa y Accesorios'), ('Vehículos', 'Vehículos'), ('Inmuebles', 'Inmuebles'), ('Servicios', 'Servicios'), ('Alimentos y Bebidas', 'Alimentos y Bebidas'), ('Salud y Bienestar', 'Salud y Bienestar'), ('Deportes y Ocio', 'Deportes y Ocio'), ('Hogar', 'Hogar'), ('Arte y Entretenimiento', 'Arte y Entretenimiento'), ('Mascotas', 'Mascotas'), ('Jardinería', 'Jardinería'), ('Herramientas y Equipos', 'Herramientas y Equipos'), ('Libros y Literatura', 'Libros y Literatura'), ('Educación y Formación', 'Educación y Formación'), ('Música', 'Música'), ('Viajes y Turismo', 'Viajes y Turismo'), ('Fotografía y Video', 'Fotografía y Video'), ('Coleccionables', 'Coleccionables'), ('Seguros', 'Seguros'), ('Servicios Profesionales', 'Servicios Profesionales')], max_length=100)),
                ('description', models.TextField(blank=True)),
                ('product_condition', models.CharField(blank=True, choices=[('Nuevo', 'Nuevo'), ('Casi nuevo', 'Casi nuevo'), ('Poco uso', 'Poco uso'), ('Usado', 'Usado'), ('Desgastado', 'Desgastado')], default='Usado', max_length=255, null=True)),
                ('publish_state', models.BooleanField(blank=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('publish_type', models.CharField(choices=[('Articulos', 'Articulos'), ('Servicios', 'Servicios'), ('Bienes', 'Bienes')], default='Articulos', max_length=255)),
                ('valor_estimado', models.IntegerField(blank=True, default=0, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MediaPublicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.FileField(null=True, upload_to='publication/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'mp4', 'mov'])])),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='publication.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/')),
                ('contract_state', models.CharField(blank=True, choices=[('Por confirmar', 'Por confirmar'), ('Activo', 'Activo'), ('Completado', 'Completado'), ('Cancelado', 'Cancelado')], max_length=100)),
                ('meeting_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_provider', to=settings.AUTH_USER_MODEL)),
                ('user_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recieving', to=settings.AUTH_USER_MODEL)),
                ('publish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, null=True)),
                ('calificacion', models.FloatField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_p', to=settings.AUTH_USER_MODEL)),
                ('user_r', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_r', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.contrato')),
                ('publish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.publicacion')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='publication.publicacion')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'publication'], name='publication_user_id_e34e3a_idx')],
                'unique_together': {('user', 'publication')},
            },
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='publication.publicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['publicacion', 'usuario'], name='publication_publica_41c8c9_idx')],
                'unique_together': {('publicacion', 'usuario')},
            },
        ),
    ]
