# Generated by Django 5.1.2 on 2024-12-15 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='user_p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_p', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='user_r',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_r', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='user_p',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_provider', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contrato',
            name='user_r',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_recieving', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.contrato'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publicacion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediapublicacion',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='publication.publicacion'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='publication.publicacion'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='publish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.publicacion'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='publish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publication.publicacion'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='publicacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='publication.publicacion'),
        ),
        migrations.AddField(
            model_name='reporte',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', 'publication'], name='publication_user_id_e34e3a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('user', 'publication')},
        ),
        migrations.AddIndex(
            model_name='reporte',
            index=models.Index(fields=['publicacion', 'usuario'], name='publication_publica_41c8c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reporte',
            unique_together={('publicacion', 'usuario')},
        ),
    ]
